### ISSUE TITLE
pp analysis scripts fail because some diagnostics are removed from diag_table.MOM6

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6-examples#58]
area_t was removed from  ice_ocean_SIS2/OM4_025/diag_table.MOM6 in commit 221f0b4b57
Some analysis scripts depend on this variable and are failing. 

```
Traceback (most recent call last):
  File "Krasting-SeaIce.py", line 22, in <module>
    yh = fs('area_t').getAxis(0)
  File "/nbhome/jpk/uvcdat-1.5/install/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 44, in __call__
    raise CDMSError, "No such variable, " + id
cdms2.error.CDMSError: No such variable, area_t
```

Also,  ssh cannot be found in ocean_daily.nc

```
 /nbhome/Niki.Zadeh/ulm_201505_intel14land_awg_v20150923_mom6sis2_2015.10.13/CM4_c96L32_am4g6_2000_sis2_lowmix_intel14/mom6/tools/analysis/calc_variance.py ssh 00010101.ocean_daily.nc /vftmp/Niki.Zadeh/pbs9188005/ulm_201505_intel14land_awg_v20150923_mom6sis2_2015.10.13/CM4_c96L32_am4g6_2000_sis2_lowmix_intel14/gfdl.ncrc2-intel14-prod-openmp/CM4_c96L32_am4g6_2000_sis2_lowmix_intel14_00010101/history_refineDiag/00010101.nc/00010101.ocean_month_refined.nc
Traceback (most recent call last):
  File "/nbhome/Niki.Zadeh/ulm_201505_intel14land_awg_v20150923_mom6sis2_2015.10.13/CM4_c96L32_am4g6_2000_sis2_lowmix_intel14/mom6/tools/analysis/calc_variance.py", line 18, in <module>
    if args.variable not in nc_in.variables: raise Exception('Could not find %s in file "%s"'%(args.variable,args.daily_file))
```

**Comment by jkrasting** [comment]
Pull request #59 should address this issue.

https://github.com/NOAA-GFDL/MOM6-examples/pull/59

--------------------------------
Dr. John Krasting
Physical Scientist (NOAA Federal)
NOAA/Geophysical Fluid Dynamics Laboratory
Biogeochemistry, Ecosystems, and Climate Group
Princeton University Forrestal Campus
201 Forrestal Road
Princeton, NJ 08540

P. (609) 452-5359
F. (609) 987-5063
